name: math_ml

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip
  - numba
  - scipy
  - pip:
      - torch>=2.1.0
      - gymnasium>=0.28.0
      - shimmy>=2.0
      - stable-baselines3>=2.0.0
      - pandas==2.1.4
      - numpy==1.24.4
      - gym
      - wandb==0.19.11
      