_wandb:
    value:
        cli_version: 0.19.11
        code_path: code/combinatorics_25/train.py
        m: []
        python_version: 3.11.12
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.12
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
algo:
    value: PPO
env:
    value: SeqGraphEnv
seed_nr:
    value: 0
